### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#142]
```
GraphQL request:2:3
1 | query lastNftListByEvent($limit: Float!, $event: String!) {
2 |   events: lastEvent(limit: $limit, offset: 0, interaction: $event) {
  |   ^
3 |     meta: value
```

```json
{
  "graphqlOriginalError": {
    "driverError": {
      "length": 184,
      "file": "dsm_impl.c",
      "severity": "ERROR",
      "routine": "dsm_impl_posix",
      "code": "53100",
      "stack": "error: could not resize shared memory segment \"/PostgreSQL.3948848140\" to 16777216 bytes: No space left on device\n    at Parser.parseErrorMessage (/squid/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/squid/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/squid/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/squid/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
      "name": "error",
      "where": "parallel worker",
      "line": "311"
    },
    "file": "dsm_impl.c",
    "line": "311",
    "code": "53100",
    "stack": "QueryFailedError: could not resize shared memory segment \"/PostgreSQL.3948848140\" to 16777216 bytes: No space left on device\n    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async DataSource.query (/squid/node_modules/typeorm/data-source/DataSource.js:334:20)\n    at async EventResolver.lastEvent (/squid/lib/server-extension/resolvers/event.js:33:24)",
    "query": "SELECT\n    DISTINCT ne.id as id,\n    ne.name as name,\n    ne.issuer as issuer,\n    ne.metadata as metadata,\n    e.current_owner,\n    me.image as image,\n    me.animation_url,\n    MAX(e.timestamp) as timestamp,\n    MAX(e.meta::bigint) as value,\n    ne.collection_id as collection_id,\n    ce.name as collection_name\n\nFROM event e\n    JOIN nft_entity ne on e.nft_id = ne.id\n    LEFT join metadata_entity me on me.id = ne.metadata\n    LEFT JOIN collection_entity ce on ne.collection_id = ce.id\nWHERE\n    e.interaction = $1\n    AND ne.burned = false\n    \nGROUP BY ne.id, me.id, e.current_owner, me.image, ce.name\nORDER BY MAX(e.timestamp) DESC\nLIMIT $2 OFFSET $3",
    "severity": "ERROR",
    "where": "parallel worker",
    "length": 184,
    "parameters": [
      "LIST",
      10,
      0
    ],
    "routine": "dsm_impl_posix"
  },
  "graphqlPath": "events",
  "graphqlQuery": "query lastNftListByEvent($limit: Float!, $event: String!) {\n  events: lastEvent(limit: $limit, offset: 0, interaction: $event) {\n    meta: value\n    timestamp\n    nftId: id\n    name\n    issuer\n    currentOwner\n    metadata\n    animationUrl\n    image\n    collection: name\n    __typename\n  }\n}\n"
}
```

**Comment by vikiival** [comment]
Was resolved by FireSquid infra
