### ISSUE TITLE
Migrate to ArrowSquid

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#283]
### Context

FireSquid hit unexpectedly EOL yesterday and therefore Rubick/Marck stopped processing blocks.

![Screenshot 2024-03-30 at 09 17 36](https://github.com/kodadot/rubick/assets/22471030/cb459873-8025-4215-85e0-94efb5bfb0e3)

### Task 

- Read [Migrate to ArrowSquid (Substrate)](https://docs.subsquid.io/sdk/resources/migrate/migrate-to-arrowsquid-on-substrate/)
- take `release-squid` branch
- `update`

- https://github.com/kodadot/stick/pull/194 can help you to navigate in case

### Logs

```
sqd:processorHttpError: Got 404 from https://kusama.archive.subsquid.io/graphql at ArchiveClient.request (/squid/node_modules/@subsquid/util-internal-http-client/lib/client.js:45:27) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async ArchiveClient.graphqlRequest (/squid/node_modules/@subsquid/util-internal-http-client/lib/client.js:268:19) at async Ingest.fetchArchiveHeight (/squid/node_modules/@subsquid/substrate-processor/lib/ingest.js:228:19) at async HandlerRunner.run (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:105:37)
```

**Comment by yangwao** [comment]
Impressive, I think until someone explicitly would like to transact we can have a look and otherwise it's p3, Assets Hub would be a better bet for now.
