### ISSUE TITLE
Unknown isHex assert

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#44]
Looks like something new

```log
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(isHex(value))

    at decodeHex (/squid/node_modules/@subsquid/scale-codec-json/lib/util.js:205:26)
    at Codec.decode (/squid/node_modules/@subsquid/scale-codec-json/lib/index.js:41:45)
    at Chain.decode (/squid/node_modules/@subsquid/substrate-processor/lib/chain.js:99:43)
    at Chain.decodeCall (/squid/node_modules/@subsquid/substrate-processor/lib/chain.js:88:21)
    at SystemRemarkCall.get asV1020 [as asV1020] (/squid/lib/types/calls.js:25:32)
    at Array.handleRemark (/squid/lib/mappings/index.js:39:58)
    at /squid/node_modules/@subsquid/substrate-processor/lib/processor.js:195:50
    at /squid/node_modules/@subsquid/substrate-processor/lib/db.js:62:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by vikiival** [comment]
Fixed by #45
